# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 034e8f51685f71203a44646b28ff58eadb4e486e9d77bf18335e01fe980ea8ced57f81b66a29a5f74864b3bc6f0e0dd1ca7a4f351924877cb70489ee68803b4d

test:
  secret_key_base: 9fb3f86a12c86f15ec8e78046226a6dfa2d3c363d87d179dbbb3fabbbc192991f2739d136586a9981c503cdaf25039c2a9e7636985d2594a8c56da291db5fb94

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
